spring:
  application:
    name: "spring-jpa"

  datasource:
    driver-class-name: org.postgresql.Driver
    password: hmzhmz114@@@
    username: postgres
    url: jdbc:postgresql://localhost:5432/student_db
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    cache: false